const actionTypes = {
  USER_AUTHENTICATE: 'USER_AUTHENTICATE',
  UPDATE_USER_LOGIN_STATUS: 'UPDATE_USER_LOGIN_STATUS',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_LOGOUT: 'USER_LOGOUT',
  GET_LEADERBOARD: 'GET_LEADERBOARD'
};

export default actionTypes;
