const actionTypes = {
  USER_AUTHENTICATE: 'USER_AUTHENTICATE',
  UPDATE_USER_LOGIN_STATUS: 'UPDATE_USER_LOGIN_STATUS',
  UPDATE_LOGIN_MESSAGE: 'UPDATE_LOGIN_MESSAGE',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_LOGOUT: 'USER_LOGOUT',
  GET_LEADERBOARD: 'GET_LEADERBOARD',
  UPDATE_LEADERBOARD: 'UPDATE_LEADERBOARD',
  FETCH_LEADERBOARD_DATA: 'FETCH_LEADERBOARD_DATA',
  START_CHALLENGE: 'START_CHALLENGE',
  UPDATE_MATCH_DATA: 'UPDATE_MATCH_DATA',
  RUN_CODE: 'RUN_CODE',
  LOCK_CODE: 'LOCK_CODE',
  UPDATE_COMPILATION_STATUS: 'UPDATE_COMPILATION_STATUS'
};

export default actionTypes;
